name: Terraform Tests

on:
  workflow_call: 
    inputs:
      DB_INSTANCE_NAME:
        description: 'DB Instance Name'
        required: true
        type: string

env:
  WORKING_DIRECTORY: './terraform'

permissions:
  contents: read
  id-token: write

jobs:
  terraform_setup:
    name: Terraform Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Assume the deploy pipeline user role
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{secrets.AWS_ASSUME_ROLE}}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{secrets.AWS_REGION }}

      - name: Terraform Init
        working-directory: ${{ env.WORKING_DIRECTORY }}
        id: init
        run: |
          make tf_init

      - name: Terraform Validate
        working-directory: ${{ env.WORKING_DIRECTORY }}
        id: validate
        run: make tf_validate

      - name: Terraform Plan
        working-directory: ${{ env.WORKING_DIRECTORY }}
        id: plan
        run: make DB_USER=${{secrets.DB_USERNAME}} DB_PW=${{secrets.DB_PASSWORD}} DB_ID=${{inputs.DB_INSTANCE_NAME}} tf_plan